$(document).ready(function(){
    $(".inputButton").click(function(){
        $(".randomNameInfo").html(function(){
          var firstName = [
            "Björn",
            "Thomas",
            "Till",
            "Silvester",
            "Lucas",
            "George",
            "Axel",
            "Tillmann",
            "Alexander",
            "Ludwig",
            "Ustin",
            "Maxim",
            "Stefan",
            "Bogdan",
            "Luka",
            "Otbert",
            "Vigor",
            "Thegan",
            "Garivald",
            "Fulrad",
            "Razo",
            "Wulfram",
            "Leuthard",
            "Turpin",
            "Otto",
            "Fulk",
            "Hubert",
            "Clovis",
            "Odo",
            "Anno",
            "Karlmann",
            "Anskar",
            "Folmar",
            "Tihomir",
            "Vlad",
            "Wella",
            "Gunteric",
            "Colias",
            "Rikiar",
            "Galindus",
            "Mundo",
            "Alaric",
            "Aligern",
            "Rodolf",
            "Eberwolf",
            "Salla",
            "Borani",
            "Bilimer",
            "Duda",
            "Agila",
            "Totila",
            "Odoin",
            "Huml",
            "Ibba",
            "Ovida",
            "Saphrax",
            "Dins",
            "Salvis",
            "Albins",
            "Egils",
            "Nocler",
            "Zuba",
            "Fograal",
            "Odlec",
            "Sokolt",
            "Kralca",
            "Stutra",
            "Muallor",
            "Dizoc",
            "Koveen",
            "Liazu",
            "Enad",
            "Suneld",
            "Derkay",
            "Asrall",
            "Kraice",
            "Dobroka",
            "Stilmul",
            "Enza",
            "Logac",
            "Okeak",
            "Aryer",
            "Hendla",
            "Drurna",
            "Thaiva",
            "Marua",
            "Kriskar",
            "Bultalt",
            "Chatar",
            "Drimi",
            "Geiblor",
            "Cothmand",
            "Dulwal",
            "Strizast",
            "Ebe",
            "Tholuk",
            "Tilcas",
            "Undlo",
            "Nultad",
            "Bruson",
            "Gritri"


          ];

          var lastName = [
            "Peters",
          ];
          //Finds first name
          var randomSelection = Math.floor(Math.random() * firstName.length);
          var names = firstName[randomSelection];

          //Finds last name
          var randomSelection = Math.floor(Math.random() * lastName.length);
          names = (names + " " + lastName[randomSelection]);

          return names;
        });
    });
});
